{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velocity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}{{ . | toYaml | nindent 4 }}{{ end }}
  annotations:
    {{- .Values.serviceAccount.annotations | toYaml | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
secrets:
  {{- .Values.serviceAccount.secrets | toYaml | nindent 2 }}
imagePullSecrets:
  {{- .Values.serviceAccount.imagePullSecrets | toYaml | nindent 2 }}
{{- end }}
