{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "velocity.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}{{ . | toYaml }}{{ end }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default .Values.proxyPort | int }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "velocity.selectorLabels" . | nindent 4 }}
{{- end }}
