{{- $apiVersion := .Values.routes.apiVersion | default .Values.global.apiVersion -}}
{{- $globalAnnotations := .Values.global.annotations | default (dict) -}}
{{- $globalLabels := .Values.global.labels | default (dict) -}}
{{- range $name, $config := omit .Values.routes "apiVersion" }}
---
apiVersion: {{ $apiVersion }}
kind: IngressRoute
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "traefik-custom-resources.labels" (dict "name" $name "context" $) | nindent 4 }}
    {{- with ($config.labels | default (dict) | mustDeepCopy | mustMergeOverwrite (mustDeepCopy $globalLabels)) }}
      {{- . | toYaml | nindent 4 }}{{ end }}
{{- with ($config.annotations | default (dict) | mustDeepCopy | mustMergeOverwrite (mustDeepCopy $globalAnnotations)) }}
  annotations:
    {{- . | toYaml | nindent 4 }}{{ end }}
spec:
  {{- omit $config "annotations" "labels" | toYaml | nindent 2 }}
{{ end -}}
