{{- $apiVersion := .Values.services.apiVersion | default .Values.common.apiVersion -}}
{{- $commonAnnotations := .Values.common.annotations | default (dict) -}}
{{- $commonLabels := .Values.common.labels | default (dict) -}}
{{- range $name, $config := omit .Values.services "apiVersion" }}
---
apiVersion: {{ $apiVersion }}
kind: TraefikService
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "traefik-custom-resources.labels" (dict "name" $name "context" $) | nindent 4 }}
    {{- with ($config.labels | default (dict) | mustDeepCopy | mustMergeOverwrite (mustDeepCopy $commonLabels)) }}
      {{- . | toYaml | nindent 4 }}{{ end }}
{{- with ($config.annotations | default (dict) | mustDeepCopy | mustMergeOverwrite (mustDeepCopy $commonAnnotations)) }}
  annotations:
    {{- . | toYaml | nindent 4 }}{{ end }}
spec:
  {{- omit $config "annotations" "labels" | toYaml | nindent 2 }}
{{ end -}}
