name: Helm

on:
  pull_request:
    branches: [main]
    paths: ["charts/**/*"]

jobs:
  chart-test:
    name: runner / test-charts
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
      - uses: helm/chart-testing-action@v2.1.0

      - run: ct lint --config $GITHUB_WORKSPACE/.github/chart-testing.yml
