name: Pull Request

on: [pull_request_target]

jobs:
  label:
    name: runner / label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
