name: Release

on:
  push:
    branches: [main]

jobs:
  helm-charts:
    name: runner / helm-charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v1
      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # github-release:
  #   name: runner / github
  #   runs-on: ubuntu-latest
  #   needs: [helm-charts]
  #   permissions:
  #     contents: write
  #     pull-requests: read

  #   steps:
  #     - uses: actions/checkout@v2

  #     - id: tag
  #       uses: mathieudutour/github-tag-action@v5.6
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}

  #     - uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ steps.tag.outputs.new_tag }}
  #         name: ${{ steps.tag.outputs.new_tag }}
  #         body: ${{ steps.tag.outputs.changelog }}
