name: Release

on:
  push:
    branches: [main]
    paths: ["charts/*/Chart.yaml"]

jobs:
  changelog:
    name: runner / changelog
    runs-on: ubuntu-latest
    container: quay.io/git-chglog/git-chglog:0.15.0

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: "apk add --update --no-cache bash yq gettext"
      - id: changed-charts
        uses: tj-actions/changed-files@v10.1
        with:
          files: charts/*/Chart.yaml

      - if: steps.changed-charts.outputs.any_changed == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          ./.github/scripts/update-chart-changelogs.sh ${{ steps.changed-charts.outputs.all_modified_files }}

  charts:
    name: runner / charts
    runs-on: ubuntu-latest
    needs: [changelog]
    container: quay.io/helmpack/chart-releaser:v1.2.1

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: "./.github/scripts/release-charts.sh"
        env:
          CR_TOKEN: ${{ secrets.ACTIONS_PAT }}
