name: Release

on:
  push:
    branches: [main]

jobs:
  changelog:
    name: runner / changelog
    runs-on: ubuntu-latest
    container: quay.io/git-chglog/git-chglog:0.15.0

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          apk add --update --no-cache bash yq gettext
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - id: changed-charts
        uses: tj-actions/changed-files@v10.1
        with:
          files: charts/*/Chart.yaml

      - if: steps.changed-charts.outputs.any_changed == 'true'
        run: |
          ./.github/scripts/update-chart-changelogs.sh ${{ steps.changed-charts.outputs.all_modified_files }}

  charts:
    name: runner / charts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v1
      - uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts
          config: .github/chart-release.yml
        env:
          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
