name: Release

on:
  push:
    branches: [main]
    paths: ["charts/*/Chart.yaml"]

jobs:
  list-changed:
    name: setup / list-changed
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      changes: ${{ steps.set-matrix.outputs.changes }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: changed-charts
        uses: tj-actions/changed-files@v11.6
        with:
          files: Chart.yaml

      - id: set-matrix
        run: |
          ./.github/scripts/list-changed.sh ${{ steps.changed-charts.outputs.all_modified_files }}

  tag:
    name: runner / tag
    runs-on: ubuntu-latest

    needs: [list-changed]
    if: needs.list-changed.outputs.changes == 'true'
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-changed.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - id: chart-version
        uses: mikefarah/yq@v4.14.1
        with:
          cmd: yq eval '.version' charts/${{ matrix.chart-name }}/Chart.yaml
      - uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ matrix.chart-name }}-${{ steps.chart-version.outputs.result }}
          tag_prefix: ""

  changelog:
    name: runner / changelog
    runs-on: ubuntu-latest
    container: quay.io/git-chglog/git-chglog:0.15.0

    needs: [tag]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PAT }}

      - run: "apk add --update --no-cache bash yq gettext"
      - id: changed-charts
        uses: tj-actions/changed-files@v11.6
        with:
          files: Chart.yaml

      - if: steps.changed-charts.outputs.any_changed == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          bash ./.github/scripts/update-chart-changelogs.sh ${{ steps.changed-charts.outputs.all_modified_files }}

  charts:
    name: runner / charts
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-releaser:v1.2.1
    needs: [changelog]

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v1
      - run: |
          apk add --update --no-cache bash
          bash ./.github/scripts/release-charts.sh
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
